function p = forward(in1)
%FORWARD
%    P = FORWARD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 12:33:41

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = q3+t2;
p = [cos(q1).*(3.0./2.0)+cos(t2).*(3.0./2.0)+cos(t3).*(3.0./2.0);sin(q1).*(3.0./2.0)+sin(t2).*(3.0./2.0)+sin(t3).*(3.0./2.0)];
