function J = Jacobian(in1)
%JACOBIAN
%    J = JACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 12:33:42

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3.*(3.0./2.0);
t9 = t5.*(3.0./2.0);
t10 = -t9;
t11 = t6.*(3.0./2.0);
t12 = t7.*(3.0./2.0);
t13 = -t12;
J = reshape([t10+t13-sin(q1).*(3.0./2.0),t8+t11+cos(q1).*(3.0./2.0),t10+t13,t8+t11,t13,t11],[2,3]);
